[build]
  command = "./build.sh"

# https://answers.netlify.com/t/web-application-manifest-mime-type/34110
[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
